package Estacionamiento;

import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

public class LoginUsuario extends javax.swing.JFrame {

    ConexionBD con = new ConexionBD();
    Connection cn = con.conexion();
    Estructura control;

    /**
     * Creates new form LoginUsuario
     */
    public LoginUsuario() {
        initComponents();
        control = new Estructura();
        setSize(665, 520);
    }

    void ingreso() {
        // Boton igresar usuario registrado 
        String sql = "SELECT * FROM usuarios", auxmatricula = "", auxocupacion = "";
        Statement st;
        try {
            st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            int auxMatriculaEntrada = Integer.parseInt(matriculaEntrada.getText());
            while (rs.next()) {
                String matricula = rs.getString(1);
                String ocupacion = rs.getString(2);
                if (matricula.equals(matriculaEntrada.getText())) {
                    auxmatricula = matricula;
                    auxocupacion = ocupacion;
                }
            }
            if (auxmatricula.equals(matriculaEntrada.getText())) {
                if (true == control.verificar(auxMatriculaEntrada)) {
                    JOptionPane.showMessageDialog(null, "Lo sentimos el auto ya entro");
                } else {
                    control.ingresarVehiculoRegistrado(auxMatriculaEntrada, auxocupacion);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Lo sentimos usted no esta registrado");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "La matricula es numerica");
        }
        matriculaEntrada.setText("");

    }

    void ingresoInvitado() {
        // Boton ingresar a un invitado
        if (nombreInvitado.getText().equals("") || placaInvitado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingresa los valores correctamente");
        } else {
            if (control.verificarInvitado(placaInvitado.getText())) {
                JOptionPane.showMessageDialog(null, "Lo sentimos el auto ya entro");
            } else {
                control.ingresarVehiculoInvitado(nombreInvitado.getText(), placaInvitado.getText());
            }
        }

        nombreInvitado.setText("");
        placaInvitado.setText("");

    }

    void salirUsuario() {
        // TODO add your handling code here:
        try {
            int auxFolioSalida = Integer.parseInt(folioSalida.getText());
            mensaje.setText(control.salir(auxFolioSalida));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "El folio es numerico");
        }
        folioSalida.setText("");

    }

    void irVentanaAdministrador() {
        // TODO add your handling code here:
        LoginAdministrador abrir = new LoginAdministrador();
        abrir.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_pestañas = new javax.swing.JTabbedPane();
        JPanel_IngresarUsuario = new javax.swing.JPanel();
        matriculaEntrada = new javax.swing.JTextField();
        ingreso = new javax.swing.JButton();
        abrirAdministrador = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel_IngresarInvitado = new javax.swing.JPanel();
        nombreInvitado = new javax.swing.JTextField();
        placaInvitado = new javax.swing.JTextField();
        ingresoInvitado = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        salir = new javax.swing.JButton();
        folioSalida = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensaje = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        salidaMensaje = new javax.swing.JTextArea();
        generar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Menu_pestañas.setMaximumSize(new java.awt.Dimension(700, 500));
        Menu_pestañas.setMinimumSize(new java.awt.Dimension(700, 500));
        Menu_pestañas.setPreferredSize(new java.awt.Dimension(700, 500));

        JPanel_IngresarUsuario.setMaximumSize(new java.awt.Dimension(670, 500));
        JPanel_IngresarUsuario.setMinimumSize(new java.awt.Dimension(670, 500));
        JPanel_IngresarUsuario.setPreferredSize(new java.awt.Dimension(670, 500));
        JPanel_IngresarUsuario.setLayout(null);

        matriculaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaEntradaActionPerformed(evt);
            }
        });
        JPanel_IngresarUsuario.add(matriculaEntrada);
        matriculaEntrada.setBounds(410, 240, 180, 40);

        ingreso.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        ingreso.setText("Ingresar");
        ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoActionPerformed(evt);
            }
        });
        JPanel_IngresarUsuario.add(ingreso);
        ingreso.setBounds(450, 310, 110, 20);

        abrirAdministrador.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        abrirAdministrador.setText("Administrador");
        abrirAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAdministradorActionPerformed(evt);
            }
        });
        JPanel_IngresarUsuario.add(abrirAdministrador);
        abrirAdministrador.setBounds(480, 400, 110, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josue-Chuwi\\Downloads\\AI_Estacionamiento_Facultad\\AI_Estacionamiento_Facultad\\src\\Imagenes\\Ingreso_Usuario.png")); // NOI18N
        jLabel8.setMinimumSize(new java.awt.Dimension(653, 468));
        JPanel_IngresarUsuario.add(jLabel8);
        jLabel8.setBounds(0, 0, 650, 450);

        Menu_pestañas.addTab("Ingresar Usuario", JPanel_IngresarUsuario);

        jPanel_IngresarInvitado.setMaximumSize(new java.awt.Dimension(670, 500));
        jPanel_IngresarInvitado.setMinimumSize(new java.awt.Dimension(670, 500));
        jPanel_IngresarInvitado.setLayout(null);

        nombreInvitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreInvitadoActionPerformed(evt);
            }
        });
        jPanel_IngresarInvitado.add(nombreInvitado);
        nombreInvitado.setBounds(420, 220, 180, 40);
        jPanel_IngresarInvitado.add(placaInvitado);
        placaInvitado.setBounds(420, 300, 180, 40);

        ingresoInvitado.setText("Ingresar");
        ingresoInvitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoInvitadoActionPerformed(evt);
            }
        });
        jPanel_IngresarInvitado.add(ingresoInvitado);
        ingresoInvitado.setBounds(430, 360, 160, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josue-Chuwi\\Downloads\\AI_Estacionamiento_Facultad\\AI_Estacionamiento_Facultad\\src\\Imagenes\\Ingresar_Invitado.png")); // NOI18N
        jPanel_IngresarInvitado.add(jLabel7);
        jLabel7.setBounds(0, 0, 653, 450);

        Menu_pestañas.addTab("Ingresar Invitado", jPanel_IngresarInvitado);

        jPanel3.setMaximumSize(new java.awt.Dimension(670, 500));
        jPanel3.setMinimumSize(new java.awt.Dimension(670, 500));
        jPanel3.setLayout(null);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel3.add(salir);
        salir.setBounds(450, 300, 100, 20);
        jPanel3.add(folioSalida);
        folioSalida.setBounds(410, 250, 180, 30);

        mensaje.setColumns(20);
        mensaje.setRows(5);
        jScrollPane1.setViewportView(mensaje);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(40, 340, 560, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josue-Chuwi\\Downloads\\AI_Estacionamiento_Facultad\\AI_Estacionamiento_Facultad\\src\\Imagenes\\Salir.png")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(653, 487));
        jLabel1.setMinimumSize(new java.awt.Dimension(653, 487));
        jLabel1.setPreferredSize(new java.awt.Dimension(653, 487));
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 450);

        Menu_pestañas.addTab("Salir", jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(670, 500));
        jPanel4.setMinimumSize(new java.awt.Dimension(670, 500));
        jPanel4.setLayout(null);

        salidaMensaje.setColumns(20);
        salidaMensaje.setRows(5);
        jScrollPane2.setViewportView(salidaMensaje);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(260, 190, 370, 200);

        generar.setText("Generar");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });
        jPanel4.add(generar);
        generar.setBounds(70, 360, 160, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Josue-Chuwi\\Downloads\\AI_Estacionamiento_Facultad\\AI_Estacionamiento_Facultad\\src\\Imagenes\\Estado_Actual.png")); // NOI18N
        jPanel4.add(jLabel2);
        jLabel2.setBounds(0, 0, 650, 450);

        Menu_pestañas.addTab("Estado del Estacionamiento", jPanel4);

        getContentPane().add(Menu_pestañas);
        Menu_pestañas.setBounds(0, 10, 1290, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoActionPerformed
        ingreso();
    }//GEN-LAST:event_ingresoActionPerformed

    private void ingresoInvitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoInvitadoActionPerformed
        ingresoInvitado();
    }//GEN-LAST:event_ingresoInvitadoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        salirUsuario();
    }//GEN-LAST:event_salirActionPerformed

    private void abrirAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAdministradorActionPerformed
        irVentanaAdministrador();
    }//GEN-LAST:event_abrirAdministradorActionPerformed

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
        // TODO add your handling code here:
        salidaMensaje.setText(control.reporte());
    }//GEN-LAST:event_generarActionPerformed

    private void nombreInvitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreInvitadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreInvitadoActionPerformed

    private void matriculaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaEntradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel_IngresarUsuario;
    private javax.swing.JTabbedPane Menu_pestañas;
    private javax.swing.JButton abrirAdministrador;
    private javax.swing.JTextField folioSalida;
    private javax.swing.JButton generar;
    private javax.swing.JButton ingreso;
    private javax.swing.JButton ingresoInvitado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_IngresarInvitado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField matriculaEntrada;
    private javax.swing.JTextArea mensaje;
    private javax.swing.JTextField nombreInvitado;
    private javax.swing.JTextField placaInvitado;
    private javax.swing.JTextArea salidaMensaje;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
